export const examples = [
    {
        id: "1",
        img: "/images/1.jpeg",
        title: "Заголовок 1",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum.",
        descriptionFull:
            "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum",
    },
    {
        id: "2",
        img: "/images/2.jpeg",
        title: "Заголовок 2",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum.",
        descriptionFull:
            "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum",
    },
    {
        id: "3",
        img: "/images/1.jpeg",
        title: "Заголовок 3",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum.",
        descriptionFull:
            "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum",
    },
    {
        id: "4",
        img: "/images/2.jpeg",
        title: "Заголовок 4",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum.",
        descriptionFull:
            "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum",
    },
    {
        id: "5",
        img: "/images/1.jpeg",
        title: "Заголовок 5",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum.",
        descriptionFull:
            "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum",
    },
    {
        id: "6",
        img: "/images/1.jpeg",
        title: "Заголовок 6",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum.",
        descriptionFull:
            "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earumLorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci, debitis dolore earum",
    },
]